version: "3.8"
networks:
  frontend:
    external: false
    name: frontend
  backend:
    external: false
    name: backend
services:
  node:
    networks:
      - frontend
    build: main-frontend/
    restart: always
    ports: 
      - 4200:80
    depends_on:
      - api_service
  mongo_db:
    networks: 
      - backend
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
  api_service:
    networks:
      - backend
    build: main-backend/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db