version: "3.9"
networks:
  frontend:
    external: false
    name: frontend
  backend:
    external: false
    name: backend
services:
  mongo_db:
    networks: 
      - backend
    image: "yowoo/my-mongo"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_store:/home/web/data
  api_service:
    networks:
      - backend
    build: main-rx-backend/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  node:
    networks:
      - frontend
    build: main-rx-frontend/
    restart: always
    ports: 
      - 4200:80
    depends_on:
      - api_service
volumes:
  mongo_store: